Repository Gulnihal/kozmotrust_alpha, pull requests merged in 2024-03, with the labels that each got.

#30 more fix for functionality
  kozmotrust/.idea/workspace.xml
  kozmotrust/lib/common/widgets/bottom_bar.dart
  kozmotrust/lib/constants/global_variables.dart
  kozmotrust/lib/features/account/screens/account_screen.dart
  kozmotrust/lib/features/account/services/account_services.dart
  kozmotrust/lib/features/account/widgets/account_button.dart
  kozmotrust/lib/features/account/widgets/below_app_bar.dart
  kozmotrust/lib/features/account/widgets/bottom_buttons.dart
  kozmotrust/lib/features/account/widgets/top_buttons.dart
  kozmotrust/lib/features/admin/screens/add_product_screen.dart
  kozmotrust/lib/features/admin/screens/admin_screen.dart
  kozmotrust/lib/features/admin/services/admin_services.dart
  kozmotrust/lib/features/allergies/screens/allergies_screen.dart
  kozmotrust/lib/features/auth/screens/auth_screen.dart
  kozmotrust/lib/features/auth/services/auth_service.dart
  kozmotrust/lib/features/favorites/screens/favorites_screen.dart
  kozmotrust/lib/features/favorites/services/favorites_services.dart
  kozmotrust/lib/features/favorites/widgets/favorite_product.dart
  kozmotrust/lib/features/gptexamine/screens/gpt_examine_screen.dart
  kozmotrust/lib/features/home/screens/category_deals_screen.dart
  kozmotrust/lib/features/home/screens/home_screen.dart
  kozmotrust/lib/features/home/services/home_services.dart
  kozmotrust/lib/features/home/widgets/allergies_box.dart
  kozmotrust/lib/features/home/widgets/deal_of_day.dart
  kozmotrust/lib/features/home/widgets/top_categories.dart
  kozmotrust/lib/features/insights/screens/add_blog.dart
  kozmotrust/lib/features/insights/screens/blog.dart
  kozmotrust/lib/features/insights/screens/blogs.dart
  kozmotrust/lib/features/product_details/screens/product_details_screen.dart
  kozmotrust/lib/features/product_details/services/product_details_services.dart
  kozmotrust/lib/features/search/screens/search_screen.dart
  kozmotrust/lib/features/search/widget/searched_product.dart
  kozmotrust/lib/main.dart
  kozmotrust/lib/models/favorites.dart
  kozmotrust/lib/models/product.dart
  kozmotrust/lib/models/user.dart
  kozmotrust/lib/providers/user_provider.dart
  kozmotrust/lib/router.dart
  kozmotrust_server/models/favorites.js
  kozmotrust_server/routes/user.js
Labels: bug, duplicate, enhancement, help wanted

#32 issue#31
  kozmotrust/lib/features/home/screens/home_screen.dart
  kozmotrust/lib/features/home/services/home_services.dart
  kozmotrust/lib/providers/user_provider.dart
Labels: bug, enhancement

#35 Issue#34
  kozmotrust/lib/common/widgets/custom_button.dart
  kozmotrust/lib/common/widgets/stars.dart
  kozmotrust/lib/constants/global_variables.dart
  kozmotrust/lib/features/account/screens/account_settings.dart
  kozmotrust/lib/features/account/services/account_services.dart
  kozmotrust/lib/features/account/widgets/account_button.dart
  kozmotrust/lib/features/account/widgets/bottom_buttons.dart
  kozmotrust/lib/features/admin/screens/add_product_screen.dart
  kozmotrust/lib/features/auth/screens/auth_screen.dart
  kozmotrust/lib/features/product_details/screens/product_details_screen.dart
  kozmotrust/lib/models/user.dart
  kozmotrust/lib/router.dart
  kozmotrust/pubspec.lock
  kozmotrust/pubspec.yaml
  kozmotrust_server/routes/auth.js
Labels: enhancement

#41 Issue#33
  kozmotrust/.idea/workspace.xml
  kozmotrust/lib/common/widgets/custom_button.dart
  kozmotrust/lib/features/account/screens/account_screen.dart
  kozmotrust/lib/features/account/screens/healthinfo_screen.dart
  kozmotrust/lib/features/gptexamine/screens/gpt_examine_screen.dart
  kozmotrust/lib/features/gptexamine/widgets/list_find_from_favorites.dart
  kozmotrust/lib/features/home/widgets/healthinfo_box.dart
  kozmotrust/lib/features/product_details/screens/product_details_screen.dart
  kozmotrust/lib/features/product_details/services/product_details_services.dart
  kozmotrust/lib/features/search/screens/search_screen.dart
  kozmotrust_server/config.js
  kozmotrust_server/routes/user.js
Labels: bug, duplicate, enhancement

#43 issue#18
  .gitignore
  kozmotrust/.idea/workspace.xml
  kozmotrust_server/config.js
  kozmotrust_server/index.js
  kozmotrust_server/node_modules/.package-lock.json
  kozmotrust_server/node_modules/dotenv/CHANGELOG.md
  kozmotrust_server/node_modules/dotenv/LICENSE
  kozmotrust_server/node_modules/dotenv/README-es.md
  kozmotrust_server/node_modules/dotenv/README.md
  kozmotrust_server/node_modules/dotenv/config.d.ts
  kozmotrust_server/node_modules/dotenv/config.js
  kozmotrust_server/node_modules/dotenv/lib/cli-options.js
  kozmotrust_server/node_modules/dotenv/lib/env-options.js
  kozmotrust_server/node_modules/dotenv/lib/main.d.ts
  kozmotrust_server/node_modules/dotenv/lib/main.js
  kozmotrust_server/node_modules/dotenv/package.json
  kozmotrust_server/package-lock.json
  kozmotrust_server/package.json
Labels: bug, enhancement
